version: "3"
services:
  tile38:
    image: tile38/tile38
    container_name: tile38
    ports:
      - 9851:9851
  location:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    links:
      - tile38
    depends_on:
      - tile38
